== Libro Tercero

=== Proposición III. Teorema III

_Que la fuerza por la que la Luna es retenida en su órbita tiende
hacia la Tierra y es inversamente proporcional al cuadrado de la
distancia de su lugar al centro de la Tierra_.

La primera parte de la Proposición se desprende manifiestamente
del Fenómeno VI y las Proposiciones II o III, Libro I; la
última del lentísimo movimiento del apogeo de la Luna, que, al
no avanzar en cada evolución más que 3°3', puede ser ignorado.
Pues del Corolario I, Proposición XLV, Libro I, se desprende
que si la distancia de la Luna al centro de la Tierra es al
semidiámetro de la Tierra como D a 1, la fuerza de la que
resultará dicho movimiento es inversamente proporcional a
D 2 4/243 es decir, inversamente proporcional a la potencia de D
cuyo exponente es 2 4/243, es decir, en la proporción de la
distancia, algo mayor que el cuadrado inverso, pero 59 3/4 veces
más cerca de la proporción acorde al cuadrado que al cubo.
Pero como este incremento se debe a la acción del Sol (como
mas adelante expondremos), aquí puede ser ignorado. La acción
de atracción del Sol sobre la Luna que tiende a alejarla de la
Tierra es aproximadamente como la distancia de la Luna a
la Tierra y, en consecuencia (según se ha expuesto en el Corolario
II, Proposición XLV, Libro I) es a la fuerza centrípeta de
la Luna como 2 a 357.45, o aproximadamente tal, es decir, como
1 a 178 29/40. Y si ignoramos esta fuerza tan imperceptible del Sol,
la fuerza restante, que retiene a la Luna en su orbe, será
inversamente proporcional a D². Esto se comprenderá con
mayor claridad aún al comparar esta fuerza con la fuerza de la
gravedad, como se hará en la siguiente Proposición.

*Colorario*. Si aumentamos la fuerza centrípeta media por
la que la Luna es retenida en su orbe, primero en la proporción
de 177 29/40 a 178 29/40 y después en ia proporción del cuadrado del
semidiámetro de la Tierra a la distancia media entre los centros
de la Luna y la Tierra, obtendremos la fuerza centrípeta de la
Luna en la superficie de la Tierra, en el supuesto de que dicha
fuerza aumente continuamente en proporción inversa al cuadra­do
de la altura al descender hacia la superficie de la Tierra.

=== Proposición X. Teorema X

_Que los movimientos de los planetas en los cielos pueden subsistir
durante un tiempo desmesurado_.

En el Escolio de la Proposición XL, Libro II, he demostrado
que un globo de agua helada que se mueva libremente por
nuestro aire perderá por la resistencia del aire 1/4586 parte de su
movimiento en el tiempo en que describe la longitud de su
semidiámetro, y la misma proporción se aplica a prácticamente
cualquier globo, sean cuales fueren su tamaño y la velocidad a la
que se mueven. Ahora bien, he determinado que la densidad de
nuestro globo de tierra es mayor que la que le correspondería si
estuviera solamente compuesto de agua, y ello de la siguiente
forma. Si todo el globo estuviera compuesto únicamente de
agua, todo aquello cuya densidad fuera inferior a la del agua
emergería y flotaría, debido a su menor gravedad especifica. En
consecuencia, si un globo de materia terrestre, cubierta por
todas partes de agua, fuera menos denso que el agua, emergería
en algún lado, y el agua, retrocediendo, se acumularía en el lado
opuesto. Y tal es la condición de nuestra tierra, en gran parte
cubierta por los mares. De no ser por su mayor densidad, la
tierra emergería de los mares y, conforme a su grado de ligereza,
se elevaría más o menos sobre su superficie, mientras el agua de
los mares caía hacia el lado opuesto. A tenor de la misma
argumentación, las manchas del Sol, que flotan sobre la materia
lúcida del mismo, son más ligeras que dicha materia, y en los
planetas, fuera cual fuera su modo de formación cuando aun
eran masas fluidas, toda la materia más pesada se hundió hacia
el centro. En consecuencia, puesto que la matería común de
nuestra tierra es en la superficie de la misma unas dos veces más
pesada que el agua, y un poco más abajo, en las minas, llega a
ser unas tres, cuatro, o a veces cinco veces mas pesada, es
probable que la cantidad total de materia de la Tierra sea cinco o
seis veces más pesada que si consistiera toda de agua, especial­
mente cuando, como antes he demostrado, la Tierra es unas
cuatro veces más densa que Júpiter. En consecuencia, si Júpiter
es un poco más denso que el agua, en el transcurso de los treinta
dias en que dicho planeta describe la longitud de 459 de sus
semidiámetros, perdería, en un medio de la misma densidad que
nuestro aire, casi una décima parte de su movimiento. Pero
como la resistencia de los medios decrece en proporción a su
peso o densidad, de forma que el agua, 13 3/5 veces mas ligera que
el mercurio, resiste menos en esa proporción, y el aire, 860 veces
más ligero que el agua, resiste menos en la misma proporción, en
los cielos, donde el peso del medio en que los planetas se
mueven disminuye enormemente, la resistencia prácticamente
desaparecerá.

En el Escolio de la Proposición XXII, Libro II, se muestra
que, a una altura de 200 millas sobre la Tierra, el aire es más
raro que en la superficie de la Tierra en una razón de 30 a
0,0000000000003998, ó como 75000000000000 a 1, aproximadamente.
En consecuencia, el planeta Júpiter, que gira en un medio
de la misma densidad que este aire superior, no perdería por la
resistencia del medio ni una 1000000simo parte de su movimien­to
en 1000000 de años. En los espacios cercanos a la Tierra la
resistencia obedece sólo al aire, las exhalaciones y los vapores.
Cuando éstos son cuidadosamente extraídos por la bomba de
aire bajo el recipiente, los cuerpos pesados caen en el interior del
recipiente con perfecta libertad y sin que pueda percibirse la
mínima resistencia; el mismo oro y el más ligero plumón,
liberados al mismo tiempo, descenderán con igual velocidad y
aunque caigan por un espacio de cuatro, seis u ocho pies,
tocarán fondo al mismo tiempo, como demuestran los experi­mentos.
En consecuencia, estando las regiones celestes perfecta­mente
libres de aire y exhalaciones, los planetas y cometas, al no
encontrar resistencia sensible en dichos espacios, continuarán su
movimiento a través de ellos por un período inmenso de tiempo.
