== El Sistema del Mundo

*§1* _La materia del firmamento es fluida_.

Era opinión extendida entre los antiguos, en los primeros
estadios de la filosofía, que las estrellas fijas permanecían
inmóviles en las partes más altas del mundo; que bajo las
estrellas fijas los planetas se trasladaban en torno al Sol; que la
Tierra, como uno de los planetas, describía un curso anual
alrededor del Sol, mientras por un movimiento diario giraba
entretanto en tomo a su propio eje, y que el Sol, como fuego
común que servia para calentar el todo, estaba fijo en el centro
del universo.

Esta fue la filosofía enseñada de antiguo por _Filolao_,
_Aristarco de Santos_, el _Platón_ maduro y toda la secta pitagórica;
y éste fue el criterio de _Anaximandro_, más antiguo aún; y el de
ese sabio rey romano, _Numa Pompilio_, que como un símbolo de
la figura del mundo con el Sol en el centro, erigió un templo
circular en honor de Vesta, ordenando que en su centro se
mantuviese un fuego perpetuo.

Los egipcios fueron precoces observadores de los cielos, y
probablemente desde entonces se diseminó esta filosofía en otras
naciones; pues de ellos y de las naciones circundantes obtuvieron
sus primeras y más sensatas nociones de filosofía los griegos, un
pueblo más dado al estudio de la filosofía que al de la
Naturaleza. Y en las ceremonias vestálicas podemos todavía
rastrear el antiguo espíritu de los egipcios, pues ofrecían sus
misterios -esto es, su filosofía sobre cosas por encima del modo
común de pensar- bajo el velo de ritos religiosos y símbolos
jeroglíficos.

No ha de negarse que _Anaxágoras_, _Demócrito_ y otros
afirmaron ocasionalmente que la Tierra poseía el centro del
mundo y las estrellas giraban hacía el oeste en torno a una
Tierra inmóvil en el centro, unas más deprisa y otras mas
despacio.

Sin embargo, todos coincidían en que los movimientos de los
cuerpos celestes se realizaban en espacios completamente libres
y vacíos de resistencia. El capricho de los orbes sólidos fue
posterior, introducido por _Eudoxo_, _Calipo_ y _Aristóteles_, cuando
la filosofía antigua empezó a declinar y a ceder su puesto a las
nuevas ficciones prevalecientes entre los _griegos_.

Pero, por encima de todo, el fenómeno de los cometas no
puede de ninguna manera tolerar la idea de orbes sólidos. Los
_caldeos_, que fueron los astrónomos más eximios de su tiempo,
consideraban a los cometas (que de antiguo habían sido conta­dos
entre los cuerpos celestes) como un tipo especial de planetas
que por describir órbitas excéntricas sólo se presentaban por
turnos a la vista, una vez en cada revolución, cuando descendían
hasta las partes más bajas de sus órbitas.

Y como la consecuencia inevitable de la hipótesis de órbitas
sólidas, mientras prevaleció, era que los cometas fuesen puestos
en espacios sublunares, cuando observaciones posteriores de los
astrónomos restauraron a los cometas en sus antiguos lugares de
los cielos superiores, esos espacios celestes se emanciparon
necesariamente de la losa de órbitas sólidas.

*§2* _El principio del movimiento circular en espacios libres_.

A partir de este momento no sabemos de qué modo
explicaron los antiguos el problema de cómo resultaban reteni­dos
los planetas dentro de ciertos vínculos en esos espacios
libres, y desviados de los cursos rectilíneos que -abandonados a
sí mismos- habrían seguido, para describir revoluciones regula­res
en órbitas curvas. Fue probablemente para dar algún tipo de
respuesta a esa dificultad por lo que se introdujeron las órbitas
sólidas.

Los filósofos posteriores pretendieron resolverla bien por la
acción de ciertos vórtices, como _Kepler_ y _Descartes_, o por algún
otro impulso o atracción, como _Borelli_, _Hooke_ y otros de
nuestra nación; pues partiendo de las leyes del movimiento, es
evidente que tales efectos deben proceder de la acción de una
fuerza u otra.

Pero nuestro propósito es sólo rastrear la cantidad y
propiedades de esa fuerza partiendo de los fenómenos (vid.
Escolio a la Proposición LXIX), y aplicar lo descubierto en
algunos casos simples como principios, gracias a los cuales
podremos calcular matemáticamente sus efectos en casos más
comprometidos; pues seria interminable e imposible someter
cada detalle a observación directa e inmediata.

Dijimos _matemáticamente_ para rehuir cualquier cuestión
sobre la naturaleza o cualidad de esta fuerza, que no pretende­mos
determinar mediante hipótesis alguna. En consecuencia, la
designamos con el nombre general de fuerza centrípeta, por
cuanto es una fuerza dirigida hacia algún centro; y en tanto
concierne más específicamente a un cuerpo en ese centro la
llamamos circunsolar, circunterrestre, circunjoviana, etc.

*§3* _La acción de fuerzas centrípetas_.

Si consideramos los movimientos de los proyectiles (vid Lib.
I Definiciones III-VIII) podremos entender fácilmente que los
planetas pueden ser retenidos en ciertas órbitas mediante fuerzas
centrípetas, pues una piedra proyectada se ve apartada de su
senda rectilínea por la presión de su propio peso y obligada a
describir en el aire una curva, cuando en virtud de la sola
proyección inicial habría debido continuar dicha senda recta, en
vez de ser finalmente atraída al suelo; y cuanto mayor es la
velocidad con la cual resulta proyectada más lejos llega antes de
caer a tierra. Podemos por eso suponer que la velocidad se
incremente hasta que la piedra describa un arco de 1, 2, 5, 10,
100, 1000 millas antes de caer, de forma que al final, superando
los límites de la Tierra, pasará al espacio sin tocarla.

AFB representa la superficie de la Tierra, C su centro, VD,
VE y VF las curvas que un cuerpo describiría si fuese proyecta­do
en dirección horizontal desde la cima de una alta montaña a
más y más velocidad (vid. Lib. III, Proposición X). Puesto que
los movimientos celestes no son prácticamente retardados por la
pequeña o nula resistencia de los espacios donde tienen lugar,
supongamos, para conservar la analogía de los casos, que en la
Tierra no hubiera aire, o al menos que éste está dotado de un
poder de resistencia nulo o muy pequeño. Entonces, por la
misma razón que el cuerpo, proyectado con menos velocidad
describe el arco menor VD y, proyectado con más velocidad, el
arco mayor VE, prosiguiendo en su camino hasta F y G al
aumentar la velocidad, si ésta sigue aumentando el cuerpo
terminará por llegar hasta bastante más allá de la circunferen­cia
de la Tierra, retornando a la montaña desde la que fue
proyectado.

Y puesto que las áreas descritas por este movimiento
mediante radio trazado a la Tierra son (por la Proposición I.
Libro I Princip. Mat.) proporcionales a sus tiempos de descrip­ción,
su velocidad al retornar a la montaña no será menos que al
principio, por lo que, reteniendo la misma velocidad, describirá
la misma curva una y otra vez, obedeciendo a la misma ley.

No obstante, si ahora suponemos que se proyectan varios
cuerpos por la dirección de lineas paralelas al horizonte desde
mayores alturas, como 5, 10, 100, 1000 ó más millas, o más bien
como muchos semidiámetros de la Tierra, dichos cuerpos, según
su particular velocidad y fuerza de gravedad a distintas alturas,
describirán arcos concéntricos a la Tierra o de diversas excentri­cidades
y seguirán girando en esas órbitas por el firmamento
igual que los planetas giran en las suyas.

*§4* _La certeza de la prueba_.

Cuando una piedra es proyectada oblicuamente, es decir, de
cualquier forma menos en dirección perpendicular, su continua
desviación hacia la Tierra de la linea recta por la que fue
proyectada es prueba tan cierta de su gravitación hacia la Tierra
como lo es su descenso directo cuando cae libremente desde una
posición de reposo. Igualmente, la desviación de la trayectoria
rectilínea de los cuerpos que se mueven por los espacios libres y
su continua deflexión hacia cualquier lugar son indicación
segura de la existencia de alguna fuerza que impele en todas
partes a dichos cuerpos hacia aquel lugar.

Supuesta la existencia de la gravedad, se sigue necesariamen­te
que todo cuerpo sobre la Tierra tiene que tender hacia abajo,
descendiendo directamente hacia ella si cae desde una posición
de reposo o al menos desviándose continuamente de la línea
recta hacia la Tierra si es proyectado oblicuamente. De la misma
manera, supuesta una fuerza dirigida hacia cualquier centro, se
seguirá con la misma necesidad que todos los cuerpos sobre los
que dicha fuerza actúa tendrán que descender directamente
hacia aquel centro, o al menos desviarse continuamente de la
línea recta y hacia él, en el caso de que se movieran oblicuamen­te
por lineas rectas.

Los dos primeros Libros de nuestros _Principios de Filosofía_
muestran cómo pueden inferirse las fuerzas de los movimientos y
cómo, dadas las fuerzas, podemos determinar los movimientos.

Suponiendo que la Tierra está en reposo y que las estrellas
fijas giran por los espacios libres en el transcurso de 24 horas, es
evidente que las fuerzas que retienen a las estrellas fijas en sus
órbitas no se dirigen hacia la Tierra, sino hacia los centros de
dichas órbitas, es decir, de los diversos círculos paralelos que las
estrellas fijas, declinando hacia ambos lados del ecuador, descri­ben
diariamente. Y también es evidente que las estrellas fijas,
mediante radios trazados a los centros de sus órbitas, describen
áreas exactamente proporcionales a los tiempos de descripción.
En consecuencia, puesto que los tiempos periódicos son iguales
(por el Corolario III de la Proposición IV, Libro I), se sigue que
las fuerzas centrípetas son como los radios de las diversas
órbitas, y que seguirán girando continuamente por las mismas
órbitas. Y del movimiento diario supuesto de los planetas se
siguen las mismas consecuencias.

La hipótesis de que las fuerzas no se dirigen hacia ningún
cuerpo del que dependen físicamente, sino hacia innumerables
puntos imagínanos en el eje de la Tierra, es excesivamente
incongruente. Más incongruente aún sería que dichas fuerzas
crecieran exactamente en proporción a las distancias a este eje
pues ello indicaría un aumento hasta la inmensidad, o más bien
hasta el infinito, mientras que las fuerzas de las cosas naturales
por lo común decrecen a medida que se alejan de la fuente de
donde fluyen. Aún más absurdo es que las áreas descritas por
una estrella no sean proporcionales a los tiempos o que sus
revoluciones no tengan lugar por la misma órbita, pues tanto las
áreas como las órbitas aumentan a medida que la estrella se
aleja del polo vecino, y el aumento del área demuestra que las
fuerzas no se dirigen hacia el eje de la Tierra. Esta dificultad
(Corolario 1, Proposición II, Libro I) obedece al doble movi­miento
que se observa en las estrellas fijas, uno diario en torno
al eje de la Tierra y otro, extremadamente lento, en tomo al eje
de la eclíptica. Su explicación requiere una composición de
fuerzas tan elaborada y variable que es difícil de reconciliar con
cualquier teoría física.

*§5* _Las fuerzas centrípetas se dirigen hacia los centros
individuales de los planetas_.

Infiero la existencia de fuerzas centrípetas dirigidas hacia los
cuerpos del Sol, la Tierra y otros planetas de la siguiente
manera.

La Luna gira en torno a nuestra Tierra, describiendo,
mediante radios trazados a su centro, áreas casi proporcionales
a los tiempos de su descripción, como evidencia su velocidad
comparada con su diámetro aparente, pues su movimiento es
más lento cuando su diámetro es menor (y su distancia, en
consecuencia, mayor) y su movimiento es más veloz cuando su
diámetro es mayor.

Las revoluciones de los satélites de Júpiter en torno a dicho
planeta son más regulares, pues describen circulos concéntricos
a Júpiter con movimiento uniforme, en la medida en que
nuestros sentidos pueden percibirlo.

También los satélites de Saturno giran en torno a este
planeta con movimientos casi circulares y uniformes, sin que
hasta ahora se haya observado excentricidad alguna que los
perturbe sensiblemente.

El aspecto lunar de Venus y Mercurio demuestra que giran
en torno al Sol. Cuando brillan llenos se encuentran en una
parte de su órbita que, con respecto a la Tierra, está allende el
Sol; cuando están medio llenos se encuentran en las partes
laterales del Sol; cuando muestran cuernos, en las partes
situadas entre la Tierra y el Sol; y a veces, interponiéndose
directamente entre la Tierra y el Sol, pasan por encima del disco
solar.

Venus describe, con movimiento casi uniforme, una órbita
casi circular y concéntrica al Sol.

Sin embargo, Mercurio, cuyo movimiento es más excéntrico,
se acerca notablemente al Sol y después se separa, pero siempre
es más veloz cuando está cerca del Sol, por lo que describe,
mediante radio trazado al Sol, áreas proporcionales a los
tiempos.

El diámetro aparente del Sol, comparado con su movimiento
aparente, nos demuestra, finalmente, que la Tierra describe en
torno al Sol, o el Sol en torno a la Tierra, mediante radios
trazados de uno a otra, áreas exactamente proporcionales a los
tiempos.

Hay experimentos astronómicos de los que se sigue, por las
Proposiciones I, II y III del primer Libro de nuestros Principios
y sus Corolarios, que existen fuerzas centrípetas dirigidas
(exactamente o sin errores considerables) hacia los centros de la
Tierra, Júpiter, Saturno y el Sol. En lo que respecta a Mercurio,
Venus, Marte y los planetas menores, la falta de experimentos
hace necesario argumentar por analogía.

*§6* _Las fuerzas centrípetas decrecen en proporción inversa al
cuadrado de las distancias a los centros de los planetas_.

El Corolario IV, Proposición IV, Libro I, muestra que dichas
fuerzas decrecen como el cuadrado inverso de la distancia, pues
los tiempos periódicos de los satélites de Júpiter son unos con
respecto a otros como la 3/2ava potencia de sus distancias al
centro de dicho planetas.

Hace mucho tiempo que se ha observado esta proporción en
esos satélites, y Mr. _Flamsteed_, que ha medido a menudo sus
distancias a Júpiter con micrómetro y mediante los eclipses de
los satélites, me dijo por carta que es tan exacta como pueden
discernir nuestros sentidos. También me envió las dimensiones
de sus órbitas determinadas por el micrómetro y reducidas a la
distancia media de Júpiter a la Tierra o al Sol. junto con los
tiempos de sus revoluciones, como puede verse seguidamente:

*§7* _Los planetas superiores giran en torno al Sol, describiendo,
mediante radios trazados al Sol áreas proporcionales a los
tiempos_.

Las fases de Marte y la proporción de sus diámetros
aparentes demuestran que este planeta gira en torno al Sol, pues
el hecho de que esté lleno cerca de su conjunción con el Sol y
giboso en sus cuadraturas prueba que lo circunda.

Dado que su diámetro aparente es unas cinco veces mayor
en oposición al Sol que en conjunción con él, y su distancia a la
Tierra inversamente proporcional a su diámetro aparente, esa
distancia será unas cinco veces menor cuando está en oposición
al Sol que cuando está en conjunción con él. Sin embargo, su
distancia al Sol será en ambos casos aproximadamente la misma
que se infiere de su aspecto giboso en las cuadraturas. Y puesto
que circunda al Sol a distancias casi iguales, aunque éstas son
muy desiguales en lo que respecta a la Tierra, mediante radios
trazados al Sol describirá áreas casi uniformes, pero mediante
radios trazados a la Tierra a veces es veloz, a veces estacionario
y a veces retrógrado.

Infiero que Júpiter, situado en una órbita más alta que
Marte, también gira en torno al Sol, con movimiento casi
uniforme, de la manera siguiente.

Mr. _Flamsteed_ me ha asegurado por carta que todos los
eclipses del satélite interior hasta ahora observados concuerdan
con esta teoría con tan considerable exactitud que nunca
difieren de la misma dos minutos de tiempo; que en el exterior el
error es un poco mayor, y en el más próximo a él apenas tres
veces mayor; que en el más próximo al interior la diferencia es
mucho mayor, aunque concuerda con sus cálculos casi tan
aproximadamente como la Luna con las tablas comunes; y que
sólo calcula los eclipses en base a los movimientos medios
corregidos por la ecuación de la luz descubierta e introducida
por Mr. _Romer_. Suponiendo, entonces, que la teoría difiere por
un error de menos de 2' del movimiento del satélite exterior,
como ya se ha dicho, y tomando el tiempo periódico
16d 18h 5m 13s a 2' de tiempo como todo el circulo de 360° al arco
1' 48'', el error de cálculo de Mr. _Flamsteed_, reducido a la órbita
del satélite, será menor de 1'48'', Dicho de otra forma, la
longitud del satélite, vista desde el centro de Júpiter, se determi­nará
con un error inferior a 1' 48''. Sin embargo, cuando el
satélite se encuentra en mitad de la sombra, esa longitud es la
misma que la longitud heliocéntrica de Júpiter, por lo que la
hipótesis aceptada por Mr. _Flamsteed_, es decir, la de _Copérnico_,
mejorada por _Kepler_ y (en lo que toca al movimiento de Júpiter)
posteriormente corregida por él mismo, representa correctamen­te
dicha longitud con un error de menos de 1' 48''. Y con esta
longitud y la longitud geocéntrica, fácil de encontrar, se determi­na
la distancia de Júpiter al Sol, que debe ser, en consecuencia,
exactamente la misma que la hipótesis supone. En efecto, ese
error máximo de 1' 48'' en la longitud heliocéntrica es casi
insensible y puede ignorarse sin problemas, pues quizá obedece a
cierta excentricidad del satélite aún no descubierta. En cualquier
caso, puesto que tanto la longitud como la distancia pueden
determinarse correctamente, se sigue por necesidad que Júpiter
describe, mediante radios trazados al Sol, áreas que cumplen las
condiciones de la hipótesis, es decir, que son proporcionales a
los tiempos.

El satélite de Saturno, según las observaciones de Mr.
_Huygens_ y el Dr. _Halley_, dos permite llegar a la misma
conclusión, aunque para confirmarla y realizar cálculos suficien­temente
exactos será necesaria una serie más larga de observa­ciones.
