== Proposición LXIX. Teorema XXIX

=== Escolio

Estas Proposiciones nos llevan a la analogía existente entre
las fuerzas centrípetas y los cuerpos centrales a los que se dirigen
habitualmente esas fuerzas; es razonable suponer que fuerzas
dirigidas hacia los cuerpos dependen de la naturaleza, y canti­dad
de esos cuerpos, como vemos que sucede en los experimen­tos
magnéticos. Y cuando se producen tales casos hemos de
calcular las atracciones de los cuerpos asignando a cada una de
sus partículas su fuerza adecuada, y hallando luego la suma de
todas. Utilizo aquí la palabra atracción en general, indicando
cualquier esfuerzo hecho por los cuerpos para aproximarse entre
si, ya sea que surja de la acción de los cuerpos mismos tendiendo
los unos hacia los otros o perturbándose los unos a los otros por
espíritus emitidos, ya sea que surja por la acción del éter o del
aire, o de cualquier medio, corpóreo o incorpóreo, de cualquier
modo que impela a los cuerpos allí situados los unos hacia los
otros. Utilizo en el mismo sentido general la palabra impulso, sin
definir en este tratado las especies o cualidades físicas de las
fuerzas y reduciéndome a investigar las cantidades y proporcio­nes
matemáticas de las mismas, como mencioné antes en las
Definiciones. En matemáticas hemos de investigar las cantidades
de las fuerzas con su proporción consiguiente en cualesquiera
condiciones supuestas; luego, cuando descendamos a la física,
compararemos esas proporciones con los fenómenos, para poder
conocer qué condiciones de esas fuerzas responden a las diversas
clases de cuerpos atractivos. Partiendo de ello podremos argu­mentar
con mayor seguridad sobre las especies físicas, las causas
y las proporciones de las fuerzas. Veamos, pues, con qué fuerzas
deben actuar entre sí cuerpos esféricos consistentes en partículas
dotadas de poderes atractivos del modo antes mencionado; y
qué tipo de movimientos se seguirán de ellas.
